import datetime as dt
import pandas as pd

def tle_to_dt(tle_date: str) -> dt.datetime:
    year = int(tle_date[:2]) + 2000
    day = float(tle_date[2:])
    return dt.datetime(year, 1, 1) + dt.timedelta(days=day - 1)

def load_satevo(buf) -> pd.DataFrame:
    """Loads the apigee and perigee values from the logs generated by SatEVO program."""
    observations = []
    while True:
        l1 = buf.readline()
        l2 = buf.readline()
        name = buf.readline()
        if not name:
            break
        observations.append((l1.strip().split(), l2.strip().split(), name.strip().split()))
    data = [
        {
            "apogee": float(obs[0][1]),
            "perigee": float(obs[0][3]),
            "date": tle_to_dt(obs[1][3])
        } for obs in observations
    ]
    df = pd.DataFrame(data)
    df = df.set_index("date", drop=True)
    return df
